The contest's link in the 'Submissions page' and 'Profile page' now redirects the user to the 'Contest details page'.
SoftUni-Internal/OpenJudgeSystem pull request #1227
Opened 2024-06-17 07:14 UTC by deyordanov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1358

2024-06-18 09:45 UTC, gogo4ds approved these changes

2024-06-18 09:46 UTC, gogo4ds requested changes

2024-06-18 09:46 UTC, gogo4ds commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/submission-grid-row/SubmissionGridRow.tsx
>      const handleParticipateInContestSubmit = useCallback(
Shouldn't this be renamed now?

2024-06-18 10:32 UTC, deyordanov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/submission-grid-row/SubmissionGridRow.tsx
>      const handleParticipateInContestSubmit = useCallback(
Done.

2024-06-20 09:20 UTC, gogo4ds approved these changes

2024-06-20 15:01 UTC, merged