Added the 'Transfer participants' functionality from Legacy Judge.
SoftUni-Internal/OpenJudgeSystem pull request #1255
Opened 2024-06-25 06:25 UTC by deyordanov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1369

2024-06-25 08:09 UTC, gogo4ds requested changes

2024-06-26 07:41 UTC, deyordanov commented on Services/Administration/OJS.Services.Administration.Data/Implementations/ContestsDataService.cs
> +                    .ThenInclude(p => p.Submissions)
Done.

2024-06-26 12:11 UTC, gogo4ds requested changes

2024-06-26 12:11 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Data/Implementations/ContestsDataService.cs
> +                    .ThenInclude(p => p.Submissions)
You can rename the method also, as now you include the submissions as well

2024-06-26 16:06 UTC, deyordanov commented on Services/Administration/OJS.Services.Administration.Data/Implementations/ContestsDataService.cs
> +                    .ThenInclude(p => p.Submissions)
Done.

2024-06-27 08:22 UTC, gogo4ds approved these changes

2024-06-27 08:31 UTC, merged