The lock can now be seen by users who are not logged in. Fixed an issue causing the contest categories' pages to load slowly
SoftUni-Internal/OpenJudgeSystem pull request #1263
Opened 2024-06-28 10:09 UTC by deyordanov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1381

2024-07-01 07:18 UTC, gogo4ds requested changes

2024-07-01 07:19 UTC, gogo4ds submitted a review, later dismissed

2024-07-01 13:41 UTC, deyordanov commented on Services/UI/OJS.Services.Ui.Business/Implementations/ContestsBusinessService.cs
> +                }
Considering the two functions: ```getPracticeResultsAreVisible``` and ```getCompeteResultsAreVisible``` , I have removed the if-else construction entirely. Additionally, I made a minor update to ```getPracticeResultsAreVisible``` to accommodate these changes.

2024-07-01 14:24 UTC, deyordanov commented on Services/UI/OJS.Services.Ui.Business/Implementations/ContestsBusinessService.cs
> +                }
Done.

2024-07-02 07:14 UTC, gogo4ds approved these changes

2024-07-02 07:21 UTC, merged