Replaced HttpExceptions with JsonError responses for submission validations.
SoftUni-Internal/OpenJudgeSystem pull request #1314
Opened 2024-08-13 09:57 UTC by deyordanov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1391

2024-08-14 08:46 UTC, shsimeonova approved these changes

2024-08-19 06:33 UTC, gogo4ds requested changes

2024-08-19 06:33 UTC, gogo4ds commented on Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Contests/ContestsGeneral.bg.resx
> +    <value>Имате необработено решение за този изпит. Моля изчакайте решението да бъде обработено.</value>
Shouldn't be "за тази задача"?

2024-08-19 06:37 UTC, deyordanov commented on Open Judge System/Web/OJS.Web/App_GlobalResources/Areas/Contests/ContestsGeneral.bg.resx
> +    <value>Имате необработено решение за този изпит. Моля изчакайте решението да бъде обработено.</value>
The exception with the given message is thrown when the user cannot have multiple solutions that are processed concurrently. Meaning, a single solution can be processed for a contest at a given time.

2024-08-19 06:57 UTC, gogo4ds approved these changes

2024-08-19 11:49 UTC, merged