Added 'MetaTags' on all public pages in Softuni Judge.
SoftUni-Internal/OpenJudgeSystem pull request #1325
Opened 2024-08-23 07:03 UTC by deyordanov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1439

2024-08-23 12:27 UTC, gogo4ds requested changes

2024-08-23 12:27 UTC, gogo4ds commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/profile/ProfilePage.tsx
> +export default ProfilePage;
Isn't `setLayout` needed?

2024-08-23 12:27 UTC, gogo4ds commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/contests/contest-details/ContestDetailsPage.tsx
> +export default ContestDetailsPage;
Isn't `setLayout` needed?

2024-08-26 07:24 UTC, deyordanov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/profile/ProfilePage.tsx
> +export default ProfilePage;
Done.

2024-08-26 07:25 UTC, deyordanov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/contests/contest-details/ContestDetailsPage.tsx
> +export default ContestDetailsPage;
Done.

2024-08-26 10:52 UTC, gogo4ds approved these changes

2024-08-26 10:55 UTC, merged