Resolved multiple issues related to the Test Runs.
SoftUni-Internal/OpenJudgeSystem pull request #1419
Opened 2024-10-09 06:20 UTC by deyordanov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1422
Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1287
Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1377

2024-10-09 08:20 UTC, gogo4ds requested changes

2024-10-09 08:34 UTC, deyordanov commented on Data/OJS.Data.Models/Tests/TestRun.cs
> +    public int ResultType { get; set; }
For consistency, I could revert it back to the enum type.

2024-10-09 12:08 UTC, gogo4ds commented on Data/OJS.Data.Models/Tests/TestRun.cs
> +    public int ResultType { get; set; }
Enum is better and conversion to int should be trivial.

2024-10-09 12:22 UTC, deyordanov commented on Data/OJS.Data.Models/Tests/TestRun.cs
> +    public int ResultType { get; set; }
Done.

2024-10-11 08:43 UTC, gogo4ds requested changes

2024-10-11 08:43 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Business/Submissions/SubmissionsBusinessService.cs
> +                            t.ResultType == (int)TestRunResultType.CorrectAnswer &&
Do you need the cast?

2024-10-11 08:43 UTC, gogo4ds commented on Services/Worker/OJS.Services.Worker.Business/Extensions/TaskResultServiceModelExtensions.cs
> +                    x.ResultType == (int)TestRunResultType.CorrectAnswer);
And here?

2024-10-11 14:49 UTC, deyordanov commented on Services/Administration/OJS.Services.Administration.Business/Submissions/SubmissionsBusinessService.cs
> +                            t.ResultType == (int)TestRunResultType.CorrectAnswer &&
Done.

2024-10-11 14:50 UTC, deyordanov commented on Services/Worker/OJS.Services.Worker.Business/Extensions/TaskResultServiceModelExtensions.cs
> +                    x.ResultType == (int)TestRunResultType.CorrectAnswer);
Done.

2024-10-11 14:53 UTC, gogo4ds submitted a review, later dismissed

2024-10-14 06:39 UTC, gogo4ds approved these changes

2024-10-14 07:09 UTC, merged