Merged breadcrumbs components and other small fixes
SoftUni-Internal/OpenJudgeSystem pull request #1441
Opened 2024-10-15 14:42 UTC by shsimeonova

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1538

2024-10-18 11:54 UTC, gogo4ds approved these changes

2024-10-18 11:55 UTC, gogo4ds requested changes

2024-10-18 11:55 UTC, gogo4ds commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/contests/contest-solution-submit/ContestSolutionSubmitPage.tsx
> +            console.log(data.contest);
Remove

2024-10-21 11:12 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/contests/contest-solution-submit/ContestSolutionSubmitPage.tsx
> +            console.log(data.contest);
Fixed

2024-10-22 07:15 UTC, gogo4ds approved these changes

2024-10-22 08:12 UTC, merged