Optimized the submission flow.
SoftUni-Internal/OpenJudgeSystem pull request #1475
Opened 2024-11-04 19:48 UTC by deyordanov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1594

2024-11-06 12:32 UTC, gogo4ds requested changes

2024-11-06 13:01 UTC, deyordanov commented on Services/Administration/OJS.Services.Administration.Business/ICheckersCacheService.cs
> +}
Done.

2024-11-06 13:01 UTC, deyordanov commented on Services/UI/OJS.Services.Ui.Business/Implementations/SubmissionsBusinessService.cs
> +        var contest = await this.contestsData.OneById(model.ContestId);
Done.

2024-11-07 10:08 UTC, gogo4ds requested changes

2024-11-07 12:36 UTC, deyordanov commented on Services/UI/OJS.Services.Ui.Business/Implementations/SubmissionsBusinessService.cs
> +        var contest = await this.contestsCache.GetContestDetailsServiceModel(model.ContestId);
We decided that the changes that will be made to the contest's cache should be done in a separate issue: https://github.com/SoftUni-Internal/exam-systems-issues/issues/1601

2024-11-07 12:39 UTC, gogo4ds approved these changes

2024-11-07 12:40 UTC, merged