Implement the AI Mentor.
SoftUni-Internal/OpenJudgeSystem pull request #1513
Opened 2024-12-03 09:49 UTC by deyordanov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1604

2024-12-04 08:18 UTC, gogo4ds requested changes

2024-12-04 08:18 UTC, gogo4ds commented on Servers/Worker/OJS.Servers.Worker/appsettings.json
> +  },
This should not be needed in the Worker

2024-12-04 09:42 UTC, deyordanov commented on Servers/Worker/OJS.Servers.Worker/appsettings.json
> +  },
Done.

2024-12-10 11:15 UTC, gogo4ds approved these changes

2024-12-11 10:27 UTC, merged