"Details" btn on submissions details page
SoftUni-Internal/OpenJudgeSystem pull request #495
Opened 2022-08-24 10:02 UTC by mishogv

Close: https://github.com/SoftUni-Internal/exam-systems-issues/issues/226

2022-08-29 11:04 UTC, Minkov requested changes

2022-08-29 11:04 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/details/SubmissionDetails.tsx
> +            await getSubmissionResults(currentSubmission.problem.id, currentSubmission.isOfficial);
Better to use **destructuring**:
```
const { problem: { id: problemId }, isOfficial } = currentSubmission;
```

2022-09-02 09:00 UTC, Minkov approved these changes

2022-09-05 07:36 UTC, shsimeonova approved these changes

2022-09-05 07:44 UTC, merged