Upgraded react, react-scripts, webpack and some packages
SoftUni-Internal/OpenJudgeSystem pull request #510
Opened 2022-09-20 11:51 UTC by Minkov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/263

2022-09-21 06:39 UTC, mishogv requested changes

2022-09-21 06:39 UTC, mishogv commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/index.tsx
> +// import { createRoot } from 'react-dom/client';
unnecessary comment

2022-09-21 13:02 UTC, mishogv approved these changes

2022-09-28 08:37 UTC, shsimeonova approved these changes

2022-09-28 12:01 UTC, merged