add sorting logic for submission tests by istrial and number
SoftUni-Internal/OpenJudgeSystem pull request #514
Opened 2022-09-26 14:36 UTC by msmner

2022-09-26 14:40 UTC, Minkov requested changes

2022-09-26 14:40 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/submission-results/SubmissionResults.tsx
> +    };
Rewrite with ternary

2022-09-26 14:57 UTC, shsimeonova commented
Is eslint enabled in your project configuration?

2022-09-26 14:57 UTC, shsimeonova requested changes

2022-09-26 14:57 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/submission-results/SubmissionResults.tsx
> +    const compareByOrderByAsc = (tr1: ITestRunDetailsType, tr2: ITestRunDetailsType) => {
Method name should be updated as it sorts by test type and order by.

2022-09-26 15:19 UTC, msmner commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/submission-results/SubmissionResults.tsx
> +    };
Done.

2022-09-26 15:20 UTC, msmner commented
> 

It is set to automatic ESlint configuration

2022-09-27 05:29 UTC, mishogv approved these changes

2022-10-03 06:34 UTC, Minkov approved these changes

2022-10-03 12:05 UTC, shsimeonova approved these changes

2022-10-03 12:06 UTC, merged