Fixed moving page bug when there is only 1 page available in /contests
SoftUni-Internal/OpenJudgeSystem pull request #515
Opened 2022-09-27 10:55 UTC by PetarNeshkov

https://github.com/SoftUni-Internal/exam-systems-issues/issues/181

2022-09-30 11:41 UTC, mishogv approved these changes

2022-10-03 06:35 UTC, Minkov approved these changes

2022-10-03 07:01 UTC, mishogv requested changes
Build and dist folders shouldn't be added to the PR

2022-10-03 09:49 UTC, shsimeonova approved these changes

2022-10-03 09:51 UTC, mishogv approved these changes

2022-10-03 09:53 UTC, merged