Add different skeletons for different strategies
SoftUni-Internal/OpenJudgeSystem pull request #518
Opened 2022-09-29 15:20 UTC by mishogv

Close: https://github.com/SoftUni-Internal/exam-systems-issues/issues/278

2022-09-30 07:50 UTC, shsimeonova commented
Have we checked if the correct skeleton is sent to the distributor and remote workers?

2022-09-30 07:50 UTC, shsimeonova commented
Please check all csthml and js files for correct crlf endings.

2022-09-30 07:50 UTC, shsimeonova requested changes

2022-09-30 07:50 UTC, shsimeonova commented on Open Judge System/Web/OJS.Web/Areas/Administration/Controllers/ProblemsController.cs
> +                x =>
please align the code here

2022-09-30 07:50 UTC, shsimeonova commented on Open Judge System/Web/OJS.Web/Controllers/TempController.cs
> +                .ProblemSubmissionTypesSkeletons.Any())
align code here so it is not on the same level as linq methods

2022-09-30 07:50 UTC, shsimeonova commented on Open Judge System/Web/OJS.Web/Controllers/TempController.cs
> +                            Console.WriteLine(ex);
please use logger

2022-09-30 07:50 UTC, shsimeonova commented on Open Judge System/Web/OJS.Web/Scripts/Administration/Problems/problems-skeletons.js
> +(() => {
please check this for crlf endings

2022-09-30 07:50 UTC, shsimeonova commented on Open Judge System/Web/OJS.Web/Controllers/TempController.cs
> +                            updatedProblemsCount++;
maybe move this after update so you don't have to decrease it in the catch block?

2022-10-03 06:30 UTC, Minkov requested changes

2022-10-03 06:30 UTC, Minkov commented on Open Judge System/Web/OJS.Web/Areas/Administration/Views/Problems/Edit.cshtml
> +﻿@using System.Web.Mvc.Expressions;
A lot of changes here. Maybe line endings? Be sure to make them `crlf`

2022-10-03 06:30 UTC, Minkov commented on Open Judge System/Web/OJS.Web/Areas/Administration/Views/Problems/EditorTemplates/SubmissionTypeViewModel.cshtml
> +﻿@using Resource = Resources.Areas.Administration.Problems.Views.EditorTemplates.SubmissionTypeViewModel;
Make sure line endings are `crlf`

2022-10-03 08:02 UTC, Minkov approved these changes

2022-10-03 08:30 UTC, shsimeonova approved these changes

2022-10-28 07:53 UTC, merged