Submissions page is ready
SoftUni-Internal/OpenJudgeSystem pull request #519
Opened 2022-10-03 06:25 UTC by Minkov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/188

2022-10-03 09:07 UTC, mishogv requested changes

2022-10-03 09:07 UTC, mishogv commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/submission-grid-row/SubmissionGridRow.module.scss
> +  .dateContainer {
is it redundant?

2022-10-03 09:07 UTC, mishogv commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/submission-grid-row/SubmissionGridRow.tsx
> +            ? 'compete'
Please use ContestParticipationType enum here

2022-10-03 11:53 UTC, mishogv approved these changes

2022-10-04 08:42 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/submission-grid-row/SubmissionGridRow.tsx
> +import styles from './SubmissionGridRow.module.scss';
You can put styles below { ContestParticipationType }.

2022-10-04 08:44 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/submissions-grid/SubmissionsGrid.tsx
> +import styles from './SubmissionsGrid.module.scss';
Same here. You can put styles below { format }.

2022-10-04 08:46 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/layout/content/PageContent.tsx
>  import styles from './PageContent.module.scss';
Same applies to here. You can put styles below import  SubmissionsPage.

2022-10-04 08:48 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/submissions/SubmissionsPage.tsx
> +
Forgotten space?

2022-10-04 08:53 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/icons/strategies/CppIcon.tsx
> +import styles from './StrategyIcon.module.scss';
We can put styles below concatClassNames.

2022-10-04 08:53 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/icons/strategies/CppIcon.tsx
> +
Forgotten space?

2022-10-04 08:54 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/icons/strategies/GoIcon.tsx
> +import styles from './StrategyIcon.module.scss';
You can put styles below concatClassNames.

2022-10-04 08:54 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/icons/strategies/GoIcon.tsx
> +
Forgotten space?

2022-10-04 08:56 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/icons/strategies/HtmlCssIcon.tsx
> +
Is this a new convention to put an empty row before styles?

2022-10-04 09:05 UTC, shsimeonova requested changes

2022-10-04 09:05 UTC, shsimeonova commented on Services/UI/OJS.Services.Ui.Business/Implementations/SubmissionsBusinessService.cs
> +        private const int DefaultPublicSubmissionsToReturn = 15;
this can be moved in GlobalConstants, we have it similar with default contests count for home page

2022-10-04 12:02 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/layout/content/PageContent.tsx
>  import styles from './PageContent.module.scss';
?

2022-10-04 12:11 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/layout/content/PageContent.tsx
>  import styles from './PageContent.module.scss';
The comment is no longer valid as you've moved the import to be at the correct position.

2022-10-04 12:13 UTC, mishogv approved these changes

2022-10-04 12:58 UTC, shsimeonova approved these changes

2022-10-04 13:25 UTC, merged