Implemented consistent titles on categories, strategies, and contest cards titles
SoftUni-Internal/OpenJudgeSystem pull request #527
Opened 2022-10-06 13:05 UTC by PetarNeshkov

https://github.com/SoftUni-Internal/exam-systems-issues/issues/182

2022-10-06 13:14 UTC, Minkov requested changes

2022-10-06 13:14 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/icons/ExpandMoreIcon.tsx
> +interface IMdExpandMoreIconProps extends IIconProps{
This should be renamed to be inline with the component

2022-10-06 13:14 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/icons/RightArrowIcon.tsx
> +interface IMdChevronRightIconProps extends IIconProps{
As above

2022-10-06 13:14 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-contests/contest-card/ContestCard.module.scss
> +  width: 225px;
Try with `max-width`:
```
width: 100%;
max-width: 225px;
```


This will simplify the mobile version... one day...

2022-10-06 13:14 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-contests/contest-card/ContestCard.module.scss
> +    width: 245px;
Same as above

2022-10-06 14:01 UTC, mishogv commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/trees/Tree.tsx
> +                    </div>
Can be extracted as a render function in order to re-use it above(line 63). 
Is this style styles.categoriesTree correctly named?

2022-10-06 14:04 UTC, Minkov requested changes

2022-10-06 14:04 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/contest-filter/ContestFilter.module.scss
> +    min-width:150px;
No. No `min-width`. Only `max-width`

2022-10-06 15:08 UTC, shsimeonova requested changes

2022-10-06 15:08 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-contests/contest-card/ContestCard.module.scss
> +    background-color: grey;
Replace this color with one  from the colors module

2022-10-06 15:08 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-contests/contest-card/ContestCard.module.scss
> +  border-bottom: 1px dotted black;
We almost have no elements using black. We have dark-gray color for this in the colors scss module

2022-10-06 15:10 UTC, shsimeonova requested changes

2022-10-06 15:10 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/trees/Tree.tsx
> +                    <div className={styles.tooltip}>
You have the same render code in a function below

2022-10-07 07:59 UTC, mishogv approved these changes

2022-10-07 12:04 UTC, shsimeonova submitted a review, later dismissed

2022-10-10 06:17 UTC, Minkov requested changes

2022-10-10 06:17 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-contests/contest-card/ContestCard.module.scss
> +    .tooltip{
Missing space

2022-10-10 11:44 UTC, shsimeonova approved these changes

2022-10-10 12:07 UTC, mishogv approved these changes

2022-10-10 12:54 UTC, Minkov approved these changes

2022-10-10 12:55 UTC, merged