Add skeletons alpha judge
SoftUni-Internal/OpenJudgeSystem pull request #530
Opened 2022-10-10 13:04 UTC by mishogv

Close: https://github.com/SoftUni-Internal/exam-systems-issues/issues/279

2022-10-10 13:18 UTC, Minkov requested changes

2022-10-10 13:18 UTC, Minkov commented on Servers/Administration/OJS.Servers.Administration/wwwroot/js/mvc-grid-form.js
> +
Better to move this code outside of this js file, since it is part of the `mvc-grid` package. Updating this package will delete this code.

2022-10-10 14:11 UTC, shsimeonova approved these changes

2022-10-11 08:01 UTC, Minkov submitted a review, later dismissed

2023-01-10 13:49 UTC, shsimeonova approved these changes

2023-07-07 09:32 UTC, shsimeonova approved these changes

2023-07-12 13:50 UTC, shsimeonova approved these changes

2023-07-13 09:24 UTC, merged