Fixed json serialization error on big test result strings
SoftUni-Internal/OpenJudgeSystem pull request #540
Opened 2022-10-19 11:07 UTC by shsimeonova

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/221

2022-10-24 11:42 UTC, Minkov approved these changes

2022-10-24 11:43 UTC, Minkov requested changes

2022-10-24 11:43 UTC, Minkov commented on Open Judge System/Web/OJS.Web/Areas/Contests/Views/Submissions/View.cshtml
> +                                    value: @Html.Raw(serializer.Serialize(testResult.ExpectedOutputFragment)) || '',
I think you changed the order here.

2022-11-07 12:23 UTC, Minkov approved these changes

2022-11-08 09:10 UTC, mishogv approved these changes

2022-11-16 15:03 UTC, merged