Make page header links` font Lato issue: https://github.com/SoftUni-In…
SoftUni-Internal/OpenJudgeSystem pull request #543
Opened 2022-10-25 11:27 UTC by msmner

Closes issue https://github.com/SoftUni-Internal/exam-systems-issues/issues/332

2022-10-26 07:41 UTC, shsimeonova submitted a review, later dismissed

2022-11-01 07:57 UTC, mishogv requested changes

2022-11-01 07:57 UTC, mishogv commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/layout/header/PageHeader.module.scss
> +  font-family: Lato, serif;
use fonts from src/styles/fonts

2022-11-02 08:49 UTC, Minkov approved these changes

2022-11-03 11:48 UTC, msmner commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/layout/header/PageHeader.module.scss
> +  font-family: Lato, serif;
Done.

2022-11-03 12:01 UTC, mishogv approved these changes

2022-11-04 12:19 UTC, Minkov approved these changes

2022-11-04 13:00 UTC, PetarNeshkov approved these changes

2022-11-04 17:20 UTC, merged