Fixed bug where Button colors for /contests page were not visualized appropriately
SoftUni-Internal/OpenJudgeSystem pull request #549
Opened 2022-10-31 07:23 UTC by PetarNeshkov

https://github.com/SoftUni-Internal/exam-systems-issues/issues/295

2022-11-02 11:57 UTC, Minkov requested changes

2022-11-02 11:57 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/contest-filter/ContestFilter.tsx
> +    strategyFilterId,
This is available in `use-contest`. There is a `state` that holds the currently selected filters

2022-11-02 11:57 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/contests-filters/ContestFilters.tsx
> +            }
Simplify this. As a rule, nested `if-else` is prohibited, unless absolutely necessary.

2022-11-02 11:57 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/contest-filter/ContestFilter.tsx
> +    onSelect: (filterId: number, filterType: FilterType) => void;
I see no reason to have the `FilterType` here.

2022-11-04 06:28 UTC, mishogv submitted a review, later dismissed

2022-11-07 11:32 UTC, shsimeonova approved these changes

2022-11-07 13:37 UTC, Minkov approved these changes

2022-11-07 14:23 UTC, merged