Cleanup skeletons alpha judge
SoftUni-Internal/OpenJudgeSystem pull request #552
Opened 2022-11-01 13:08 UTC by mishogv

close: https://github.com/SoftUni-Internal/exam-systems-issues/issues/283

2022-11-07 11:30 UTC, shsimeonova submitted a review, later dismissed

2023-01-10 13:43 UTC, shsimeonova approved these changes

2023-05-16 20:56 UTC, gogo4ds requested changes

2023-05-16 20:56 UTC, gogo4ds commented on Services/Common/OJS.Services.Common/Implementations/SubmissionsDistributorCommunicationService.cs
> +                    SolutionSkeleton = submission.Problem
Update this to be `TaskSkeleton = ...` as this is the new name that the worker expects.

2023-06-01 08:55 UTC, gogo4ds requested changes
Why so many file changes?

2023-07-12 09:20 UTC, msmner commented
Closing this one as it is a duplicate of https://github.com/SoftUni-Internal/OpenJudgeSystem/pull/530.

2023-07-25 05:43 UTC, closed without merging