Add time between submissions message
SoftUni-Internal/OpenJudgeSystem pull request #573
Opened 2022-11-22 13:03 UTC by shsimeonova

2022-11-22 13:21 UTC, PetarNeshkov approved these changes

2022-11-22 14:46 UTC, Minkov requested changes

2022-11-22 14:46 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/submission-box/SubmissionBox.tsx
> +    const [ showSubmissionLimitTimer, setShowSubmissionLimitTimer ] = useState<boolean>(true);
Isn't this the same as:
```
const showSubmissionLimitTimer = useMemo(
 () => submitLimit > 0,
 [submitLimit],
);
```

2022-11-22 14:46 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/submission-box/SubmissionBox.tsx
> +    const submissionLimitCountdownRender = useCallback((remainingTime: ICountdownRemainingType) => {
`renderSubmissionLimitCountdown`

2022-11-22 14:46 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/alert-box/AlertBox.tsx
> +        return baseClsName;
```
return hide
    ? concatClassNames(styles.hidden, baseClsName)
    : baseClsName;
```

2022-11-22 14:46 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/alert-box/AlertBox.tsx
> +    const [ hide, setHide ] = useState<boolean>(false);
`isHidden`?

2022-11-22 14:46 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/hooks/submissions/use-submissions.tsx
> +    const [ submitSuccessful, setSubmitSuccessful ] = useState<boolean | null>(null);
`const isSubmissionSucessful = useMemo(() => isSuccess, [isSuccess])`

2022-11-22 14:46 UTC, Minkov commented on Services/UI/OJS.Services.Ui.Business/Implementations/ParticipantsBusinessService.cs
> +            => Task.FromResult(this.submissionsData.GetUserSubmissionTimeLimit(participantId, contestLimitBetweenSubmissions));
```
this.submissionsData.GetUserSubmissionTimeLimit(participantId, contestLimitBetweenSubmissions)
 .ToTask()
```

2022-11-22 16:27 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/contests/submission-box/SubmissionBox.tsx
> +    const [ showSubmissionLimitTimer, setShowSubmissionLimitTimer ] = useState<boolean>(true);
yes

2022-11-23 13:24 UTC, Minkov approved these changes

2022-11-23 14:33 UTC, PetarNeshkov approved these changes

2022-11-28 11:51 UTC, merged