add max number of active and past contests to display on home page
SoftUni-Internal/OpenJudgeSystem pull request #578
Opened 2022-11-29 10:39 UTC by msmner

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/354

2022-11-29 11:36 UTC, mishogv requested changes

2022-11-29 11:36 UTC, mishogv commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/home-contests/HomeContests.tsx
> +        (contests: IIndexContestsType[]) => contests.slice(0, maxContestsToDisplay),
Send count to BE and return exact contests from controller instead of loading all and then slice it on FE

2022-11-30 07:20 UTC, mishogv approved these changes

2022-11-30 09:06 UTC, shsimeonova approved these changes

2022-11-30 09:07 UTC, PetarNeshkov approved these changes

2022-11-30 09:13 UTC, merged