Fix results page not loading
SoftUni-Internal/OpenJudgeSystem pull request #597
Opened 2022-12-19 13:47 UTC by msmner

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/430

2022-12-19 14:11 UTC, Minkov requested changes

2022-12-19 14:11 UTC, Minkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/contest-results/ContestResultsPage.tsx
> +    if (isNil(contestResults) || (typeof contestResults.results === 'undefined')) {
`typeof contestResults.results === 'undefined'` - No.
```
const { results } = contestResults || {};
if(isNil(results)) {
 ... 
}
```

2022-12-21 09:28 UTC, msmner commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/contest-results/ContestResultsPage.tsx
> +    if (isNil(contestResults) || (typeof contestResults.results === 'undefined')) {
Corrected.

2022-12-22 10:22 UTC, Minkov approved these changes

2022-12-22 10:22 UTC, PetarNeshkov approved these changes

2022-12-22 15:21 UTC, merged