Submissions file upload form
SoftUni-Internal/OpenJudgeSystem pull request #601
Opened 2023-01-16 14:56 UTC by shsimeonova

https://github.com/SoftUni-Internal/exam-systems-issues/issues/355

2023-01-16 14:59 UTC, shsimeonova commented on Services/UI/OJS.Services.Ui.Business/Implementations/SubmissionsBusinessService.cs
> +    public async Task SubmitFileSubmission(SubmitFileSubmissionServiceModel participantSubmission)
https://github.com/SoftUni-Internal/exam-systems-issues/issues/498

2023-01-17 10:00 UTC, mishogv requested changes

2023-01-17 10:14 UTC, shsimeonova commented on Services/UI/OJS.Services.Ui.Business/Implementations/SubmissionsBusinessService.cs
> +    public async Task SubmitFileSubmission(SubmitFileSubmissionServiceModel model)
https://github.com/SoftUni-Internal/exam-systems-issues/issues/498

2023-01-18 07:30 UTC, mishogv approved these changes

2023-01-18 11:10 UTC, msmner approved these changes

2023-01-24 11:18 UTC, merged