Convert time from UTC to local time
SoftUni-Internal/OpenJudgeSystem pull request #636
Opened 2023-03-14 17:03 UTC by msmner

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/497

2023-03-15 09:22 UTC, shsimeonova requested changes

2023-03-15 09:22 UTC, shsimeonova commented on Data/Infrastructure/OJS.Data.Infrastructure/DateTimeConverters/UtcToLocalDateTimeConverter/DelegatingDbDataReader.cs
> +namespace OJS.Data.Infrastructure.DateTimeConverters.UtcToLocalDateTimeConverter;
Move file to Infrastructure level

2023-03-15 09:23 UTC, shsimeonova approved these changes

2023-03-15 12:22 UTC, msmner commented on Data/Infrastructure/OJS.Data.Infrastructure/DateTimeConverters/UtcToLocalDateTimeConverter/DelegatingDbDataReader.cs
> +namespace OJS.Data.Infrastructure.DateTimeConverters.UtcToLocalDateTimeConverter;
Done.

2023-03-16 14:30 UTC, PetarNeshkov approved these changes

2023-03-16 14:55 UTC, shsimeonova approved these changes

2023-03-16 14:56 UTC, merged