Fixed a bug in which regular user has no access to contests
SoftUni-Internal/OpenJudgeSystem pull request #647
Opened 2023-03-31 15:33 UTC by PetarNeshkov

Closes: https://github.com/SoftUni-Internal/exam-systems-issues/issues/609

2023-04-01 06:30 UTC, shsimeonova requested changes

2023-04-01 06:30 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/problems/problem-submissions/ProblemSubmissions.tsx
> +                return renderErrorHeading(detail);
This should not be a heading. Make it a regular paragraph.

2023-04-03 11:39 UTC, shsimeonova requested changes

2023-04-03 11:39 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/problems/problem-submissions/ProblemSubmissions.tsx
> +                return renderErrorHeading(detail);
Rename functions

2023-04-06 05:51 UTC, mishogv submitted a review, later dismissed

2023-04-06 10:47 UTC, shsimeonova requested changes

2023-04-06 10:47 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/problems/problem-submissions/ProblemSubmissions.module.scss
> +  font-family: Lato, serif;
extend from font mixins

2023-04-11 06:27 UTC, mishogv submitted a review, later dismissed

2023-04-11 13:02 UTC, shsimeonova requested changes

2023-04-11 13:02 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/problems/problem-submissions/ProblemSubmissions.tsx
> +                return renderErrorParagraph(detail);
No point in splitting this in 2 render functions

2023-04-11 13:02 UTC, shsimeonova commented on Services/UI/OJS.Services.Ui.Business/Validations/Implementations/Contests/ContestValidationMessages.cs
> +        public const string ProblemSubmissionsNotAvailable = "You cannot view the submissions results for this problem.";
submission*

2023-04-13 07:02 UTC, shsimeonova approved these changes

2023-04-18 08:54 UTC, mishogv approved these changes

2023-04-19 11:54 UTC, merged