Fix contest categories bug
SoftUni-Internal/OpenJudgeSystem pull request #666
Opened 2023-05-08 12:57 UTC by msmner

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/585

2023-05-12 11:37 UTC, gogo4ds approved these changes

2023-05-17 13:33 UTC, gogo4ds approved these changes

2023-05-17 13:35 UTC, gogo4ds requested changes
Testing again

2023-05-17 13:42 UTC, gogo4ds approved these changes

2023-05-19 15:18 UTC, PetarNeshkov approved these changes

2023-05-25 12:20 UTC, shsimeonova submitted a review, later dismissed

2023-05-25 14:11 UTC, gogo4ds submitted a review, later dismissed

2023-05-26 13:47 UTC, msmner commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/hooks/use-contest-categories-breadcrumb.tsx
> +    const [ selectedBreadcrumbCategoryId, setSelectedBreadcrumbCategoryId ] = useState<string>('');
Done.

2023-05-26 13:51 UTC, PetarNeshkov approved these changes

2023-05-29 12:32 UTC, gogo4ds approved these changes

2023-05-29 12:34 UTC, merged