Display more detailed erro to admin and lectors
SoftUni-Internal/OpenJudgeSystem pull request #695
Opened 2023-06-09 11:08 UTC by MTsatsarov

New Exception types were added to help with debugging eventual exceptions.
Should catch every error and display detailed information on the UI if you are admin or lector

Closes [https://github.com/SoftUni-Internal/exam-systems-issues/issues/719](url)
NOTE: There is another PR inside the workers related to this issue.

2023-06-12 09:53 UTC, gogo4ds requested changes

2023-06-12 09:53 UTC, gogo4ds commented on Open Judge System/Data/OJS.Data/Migrations/202306071340433_ExectuionCommentAndExceptionType.cs
> +            AddColumn("dbo.Submissions", "ExecutionComment", c => c.String());
We are using automatic migrations in the old Judge, so no need to add manual migration. Do test it first though, as I haven't made automatic migrations recently..

2023-06-12 09:53 UTC, gogo4ds commented on Open Judge System/OJS.Common/Models/ExceptionType.cs
> +    }
Better use the enums from the workers repo, instead of duplicating them.

2023-06-13 10:45 UTC, mishogv requested changes

2023-06-13 10:45 UTC, mishogv commented on Open Judge System/Web/OJS.Web/Areas/Contests/Views/Submissions/View.cshtml
> +        </pre>
Format correctly

2023-06-16 14:16 UTC, gogo4ds submitted a review, later dismissed

2023-06-16 14:16 UTC, gogo4ds commented
Can you link the related PR in this one?

2023-06-20 14:16 UTC, gogo4ds requested changes

2023-06-21 07:00 UTC, mishogv approved these changes

2023-06-21 08:12 UTC, gogo4ds submitted a review, later dismissed

2023-06-26 09:24 UTC, gogo4ds approved these changes

2023-06-26 10:12 UTC, merged