Regular user contest entry
SoftUni-Internal/OpenJudgeSystem pull request #696
Opened 2023-06-09 13:34 UTC by PetarNeshkov

Closes: https://github.com/SoftUni-Internal/exam-systems-issues/issues/722

2023-06-09 14:12 UTC, gogo4ds requested changes

2023-06-09 14:12 UTC, gogo4ds commented on Services/UI/OJS.Services.Ui.Business/Implementations/ParticipantsBusinessService.cs
> +
We should not assign random problems to users in Practice mode. Also will this work if the contest is not Online?

2023-06-13 18:18 UTC, PetarNeshkov commented on Services/UI/OJS.Services.Ui.Business/Implementations/ContestsBusinessService.cs
> +            => !isAdmin && isOfficial && isContestOnline;
I totally agree with you. In this way, it is far more understandable and readable for people who see the business logic for first time. I refactored it to work in the that you showed it.

2023-06-14 12:56 UTC, gogo4ds submitted a review, later dismissed

2023-06-15 13:36 UTC, gogo4ds approved these changes

2023-06-19 10:27 UTC, merged