Add last execution on column in submission
SoftUni-Internal/OpenJudgeSystem pull request #699
Opened 2023-06-12 11:53 UTC by msmner

[Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/your_issue_number](https://github.com/SoftUni-Internal/exam-systems-issues/issues/725

**Summary of the changes made**:
1. Added column last execution on to submissions table
2. Retrieve the data for last execution on from a processed submission

2023-06-16 10:25 UTC, msmner commented on Data/OJS.Data/Migrations/20220325170939_InitialMigration.cs
> +                    LastExecutionOn = table.Column<DateTime>(type: "datetime2", nullable: true),
I fixed this and added a new migration instead.

2023-06-16 14:07 UTC, gogo4ds approved these changes

2023-06-16 14:12 UTC, gogo4ds requested changes
Can you name the column `StartedExecutionOn` as this is the name that is in `master` branch

2023-06-26 06:23 UTC, msmner commented
Related PRs: 
https://github.com/SoftUni-Internal/judge-submissions-distributor/pull/16
https://github.com/SoftUni-Internal/judge-worker/pull/137
https://github.com/SoftUni-Internal/interactive/pull/1584

2023-06-26 09:28 UTC, gogo4ds approved these changes

2023-06-29 11:21 UTC, gogo4ds approved these changes

2023-06-29 13:02 UTC, merged