Adding image button type
SoftUni-Internal/OpenJudgeSystem pull request #712
Opened 2023-06-21 06:01 UTC by yvmarkovska

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/523

**Summary of the changes made**:
1. Added image type to ButtonType and LinkButtonType
2. Added imgSrc and altText to BaseButtonProps
3. Made changes to button and linkbutton components
4. Added css styling for the image type button

2023-06-21 06:16 UTC, PetarNeshkov submitted a review, later dismissed

2023-06-21 06:42 UTC, gogo4ds approved these changes

2023-06-23 14:31 UTC, PetarNeshkov submitted a review, later dismissed

2023-06-27 11:35 UTC, PetarNeshkov submitted a review, later dismissed

2023-06-27 11:47 UTC, gogo4ds requested changes

2023-06-27 11:47 UTC, gogo4ds commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/buttons/Button.tsx
> +    [LinkButtonType.image]: styles.image,
Seems this is no longer needed here

2023-06-28 11:52 UTC, gogo4ds approved these changes

2023-06-29 13:12 UTC, merged