Refactor delete and copy functionalities in admin
SoftUni-Internal/OpenJudgeSystem pull request #758
Opened 2023-07-21 13:04 UTC by PetarNeshkov

Closes: https://github.com/SoftUni-Internal/exam-systems-issues/issues/787#event-9795243301

**Summary of the changes made**:
1. Made delete all page visible and workable
2. Fixed copy all functionality and added evaluation of problems and problemGroups

2023-07-26 06:38 UTC, shsimeonova requested changes

2023-07-26 06:38 UTC, shsimeonova commented on Services/Administration/OJS.Services.Administration.Business/Implementations/ProblemGroupsBusinessService.cs
> +                Name = problem.Name,
Can you do this using AutoMapper?

2023-08-01 06:35 UTC, yvmarkovska submitted a review, later dismissed

2023-08-08 06:59 UTC, shsimeonova approved these changes

2023-08-09 06:04 UTC, yvmarkovska approved these changes

2023-08-09 10:04 UTC, shsimeonova submitted a review, later dismissed

2023-08-10 09:37 UTC, msmner approved these changes

2023-08-10 14:11 UTC, merged