Fixed a bug which "Copy аll" functionаlity deletes all tests and problem resources
SoftUni-Internal/OpenJudgeSystem pull request #786
Opened 2023-08-11 11:00 UTC by PetarNeshkov

Closes: https://github.com/SoftUni-Internal/exam-systems-issues/issues/862

**Summary of the changes made**:
1.  Implemented custom mapping for ProblemResources and Tests
2.  Ignored the mapping for Tests and ProblemResources in Problems in order to not override duplicate entities

2023-08-13 09:23 UTC, gogo4ds requested changes

2023-08-13 09:23 UTC, gogo4ds commented on Data/OJS.Data.Models/Problems/ProblemResource.cs
> +                    opt => opt.MapFrom(src => 0));
This should not be here. It is not mapping logic, but business operation logic. Also entity models should be kept clean from mapping configurations.

2023-08-13 09:23 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Business/Implementations/ProblemGroupsBusinessService.cs
> +                System.Console.WriteLine(newTest.Id);
♻️

2023-08-13 09:23 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Business/Implementations/ProblemGroupsBusinessService.cs
> +                await this.testsData.SaveChanges();
Better move SaveChanges outside the loop, to improve performance.

2023-08-13 09:23 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Business/Implementations/ProblemGroupsBusinessService.cs
> +                await this.problemResourcesData.SaveChanges();
Same here

2023-08-13 09:23 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Business/Implementations/ProblemGroupsBusinessService.cs
> +                var newResource = problemResource.Map<ProblemResource>();
No need to `Map`, just use existing `problemResource`.

2023-08-13 09:23 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Business/Implementations/ProblemGroupsBusinessService.cs
> +                .ToListAsync();
Call `.AsNoTracking()` and reuse the retrieved entities to generate new ones (just clear the Id)

2023-08-13 09:23 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Business/Implementations/ProblemGroupsBusinessService.cs
> +                var newTest = test.Map<Test>();
Same here. No need to Map the same entity type.

2023-08-15 05:25 UTC, gogo4ds submitted a review, later dismissed

2023-08-15 09:20 UTC, softuni-build approved these changes

2023-08-15 09:21 UTC, gogo4ds approved these changes

2023-08-15 11:10 UTC, merged