Added default query filter for deleted problems on submission entity
SoftUni-Internal/OpenJudgeSystem pull request #791
Opened 2023-08-16 09:15 UTC by shsimeonova

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/850

**Summary of the changes made**:
Global query filter for filtering out submissions with deleted problems was missing, thus why submissions for `/submissions` page were loaded with `"problem": null`

2023-08-16 09:17 UTC, yvmarkovska approved these changes

2023-08-16 09:22 UTC, gogo4ds requested changes

2023-08-16 09:22 UTC, gogo4ds commented on Data/OJS.Data/OjsDbContext.cs
> +                .HasQueryFilter(x => !x.Problem!.IsDeleted);
We should make Problem required or add check for Problem != null

2023-09-05 14:05 UTC, gogo4ds approved these changes

2023-09-08 14:11 UTC, merged