Fix error, created Alert component
SoftUni-Internal/OpenJudgeSystem pull request #795
Opened 2023-08-22 12:47 UTC by MTsatsarov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/832

2023-08-31 08:35 UTC, shsimeonova requested changes

2023-08-31 08:36 UTC, shsimeonova requested changes

2023-08-31 08:36 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/alert/Alert.tsx
> +              sx={{ backgroundColor: `${(severity === AlertSeverity.Success)}` && 'rgb(245, 78, 84)' }}
this is odd

2023-08-31 09:19 UTC, MTsatsarov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/alert/Alert.tsx
> +import React, { useState } from 'react';
Yes

2023-08-31 09:19 UTC, MTsatsarov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/alert/Alert.tsx
> +              sx={{ backgroundColor: `${(severity === AlertSeverity.Success)}` && 'rgb(245, 78, 84)' }}
Refactored

2023-08-31 11:35 UTC, shsimeonova requested changes

2023-08-31 11:35 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/alert/Alert.tsx
> +    console.log(severity);
Remove console log

2023-08-31 11:35 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/alert/Alert.module.scss
> +.success-alert{
Space before opening bracket

2023-08-31 14:19 UTC, MTsatsarov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/guidelines/alert/Alert.module.scss
> +.success-alert{
Done

2023-09-01 09:02 UTC, shsimeonova submitted a review, later dismissed

2023-09-01 10:51 UTC, shsimeonova approved these changes

2023-09-01 10:54 UTC, merged