FIxed ContestCategories sections in Admin to work appropriate with tree UI
SoftUni-Internal/OpenJudgeSystem pull request #802
Opened 2023-08-24 05:50 UTC by PetarNeshkov

Closes : https://github.com/SoftUni-Internal/exam-systems-issues/issues/833

**Summary of the changes made**:
1. Implemented memory cache to work for administration
2. Implemented email sending on remove logic in cacheService
3. Implemented validation for empty values in ContestCategoriesController
4. Changed logic to be asynchronous
5. Changed the logic to place an empty Parent and when there is no selected Parent

2023-08-31 08:22 UTC, shsimeonova requested changes

2023-08-31 08:22 UTC, shsimeonova commented on Services/Infrastructure/OJS.Services.Infrastructure/Cache/Implementations/CacheService.cs
> +                if (this.ShouldSendExceptionEmail(
Move this if into a separate method

2023-09-07 11:39 UTC, MTsatsarov approved these changes

2023-09-11 12:54 UTC, shsimeonova approved these changes

2023-09-11 14:42 UTC, merged