Display message and retest button, when tests changed for problem
SoftUni-Internal/OpenJudgeSystem pull request #820
Opened 2023-08-31 13:46 UTC by MTsatsarov

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/874

Added new function which renders, specific message and "Retest" button, on the submission details page, when tests for the submission's problem are changed.

2023-08-31 14:04 UTC, shsimeonova requested changes

2023-08-31 14:04 UTC, shsimeonova commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/details/SubmissionDetails.module.scss
> +  font-family:  Lato, serif;
Theres a font variable for this.

2023-08-31 14:17 UTC, MTsatsarov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/components/submissions/details/SubmissionDetails.module.scss
> +  font-family:  Lato, serif;
Fixed

2023-09-01 10:14 UTC, MTsatsarov commented
Mistaken, it is created a new one https://github.com/SoftUni-Internal/OpenJudgeSystem/pull/824

2023-09-01 10:14 UTC, closed without merging