Added python depedencies configs
SoftUni-Internal/OpenJudgeSystem pull request #855
Opened 2023-09-19 14:10 UTC by PetarNeshkov

2023-09-19 14:37 UTC, shsimeonova requested changes

2023-09-19 14:37 UTC, shsimeonova commented on Docker/Dockerfile.worker
> +FROM ghcr.io/softuni-internal/19_09_2023
invalid package name

2023-09-19 14:37 UTC, shsimeonova commented on Docker/applications/worker/Judge_Linux/Dockerfile
> +FROM ghcr.io/softuni-internal/linux_base:19_09_2023
invalid

2023-09-19 14:54 UTC, gogo4ds commented
This should be merged after the Hackaton

2023-10-04 14:39 UTC, gogo4ds submitted a review, later dismissed

2023-10-06 12:12 UTC, gogo4ds approved these changes

2023-10-06 15:16 UTC, merged