Removed unnesessary register of Hangfire in UI
SoftUni-Internal/OpenJudgeSystem pull request #862
Opened 2023-09-27 11:51 UTC by shsimeonova

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/892

2023-09-27 13:36 UTC, gogo4ds requested changes

2023-09-27 13:36 UTC, gogo4ds commented on Servers/UI/OJS.Servers.Ui.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> -                .AddHangfireServer(AppName)
Will this break existing background jobs in UI?

2023-10-05 10:18 UTC, gogo4ds submitted a review, later dismissed

2023-10-05 15:25 UTC, yvmarkovska approved these changes

2023-10-10 10:56 UTC, closed without merging

2023-10-10 10:57 UTC, shsimeonova commented
https://github.com/SoftUni-Internal/OpenJudgeSystem/pull/885