Lecturers permissions
SoftUni-Internal/OpenJudgeSystem pull request #895
Opened 2023-10-16 12:29 UTC by shsimeonova

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/962

Linked pull requests from another repos (if any):

**Summary of the changes made**:
1. {Describe your changes in the list}
2.

2023-10-17 13:31 UTC, yvmarkovska submitted a review, later dismissed

2023-10-23 13:30 UTC, shsimeonova commented on Services/UI/OJS.Services.Ui.Business/Implementations/ContestResultsBusinessService.cs
> +        results.UserHasContestRights = this.lecturersInContestsBusinessService.IsUserAdminOrLecturerInContest(contest);
Fixed on FE

2023-10-23 13:38 UTC, yvmarkovska approved these changes

2023-10-27 16:55 UTC, PetarNeshkov requested changes

2023-10-27 16:55 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/ClientApp/src/pages/submissions/SubmissionsPage.tsx
> +            if (!user.isAdmin) {
There is already a useEffect which calls loadTotalUnprocessedSubmissionsCount in SubmissionGrid.tsx. This causes the query to execute two times.

2023-10-31 14:23 UTC, msmner submitted a review, later dismissed

2023-10-31 14:23 UTC, msmner commented on Services/Administration/OJS.Services.Administration.Business/ILecturerContestPrivilegesBusinessService.cs
> +    public Expression<Func<Problem, bool>> GetProblemsUserPrivilegesExpression(
Remove public

2023-11-01 09:39 UTC, msmner approved these changes

2023-11-01 14:07 UTC, PetarNeshkov approved these changes

2023-11-21 08:43 UTC, merged