update autocruadmin version to 1.1.27
SoftUni-Internal/OpenJudgeSystem pull request #910
Opened 2023-10-26 12:08 UTC by msmner

Linked pull requests from another repos (if any):

**Summary of the changes made**:
1. Updated Autocrudadmin version to 1.1.27

2023-10-31 13:04 UTC, gogo4ds requested changes

2023-10-31 13:04 UTC, gogo4ds commented on Servers/Administration/OJS.Servers.Administration/Controllers/ProblemsController.cs
> +            }
Why this is part of this PR?

2023-11-01 07:03 UTC, msmner commented on Servers/Administration/OJS.Servers.Administration/Controllers/ProblemsController.cs
> +            }
Removed as discussed.

2023-11-02 07:13 UTC, shsimeonova approved these changes

2023-11-10 09:00 UTC, shsimeonova approved these changes

2023-11-10 14:32 UTC, gogo4ds requested changes

2023-11-10 14:32 UTC, gogo4ds commented on Servers/Administration/OJS.Servers.Administration.Infrastructure/OJS.Servers.Administration.Infrastructure.csproj
> +      <PackageReference Include="AutoCrudAdmin" Version="1.1.28" />
We have newer version - 1.1.29

2023-11-14 07:29 UTC, closed without merging

2023-11-14 07:29 UTC, msmner commented
Updating to 1.1.29 was done in another PR, so I am closing this one.