Add TotalScore Snapshot
SoftUni-Internal/OpenJudgeSystem pull request #916
Opened 2023-11-01 06:20 UTC by SvetoslavUzunov

Closes: https://github.com/SoftUni-Internal/exam-systems-issues/issues/821

Added two new properties to Participant entity: 
int TotalScoreSnapshot
Datetime? TotalScoreSnapshotModifiedOn

These properties will be updated/calculated everytime user submits a submission.

Two new Background jobs added.

Background job that will update participant total score once per day. Background job that will remove Participant scores if there are more than one for specific problem , for practice or compete. It will remain only the one with highest points.

2023-11-02 06:16 UTC, MTsatsarov requested changes

2023-11-02 06:16 UTC, MTsatsarov commented on Data/Infrastructure/OJS.Data.Infrastructure/Extensions/DbContextOptionsBuilderExtensions.cs
Revert changes.

2023-11-02 06:16 UTC, MTsatsarov commented on Data/OJS.Data/OJS.Data.csproj
> +      </PackageReference>
Why are these packages added ?

2023-11-02 06:16 UTC, MTsatsarov commented on Servers/Administration/OJS.Servers.Administration/OJS.Servers.Administration.csproj
> +      <ProjectReference Include="..\..\..\Services\UI\OJS.Services.Ui.Business\OJS.Services.Ui.Business.csproj" />
Same here

2023-11-02 06:16 UTC, MTsatsarov commented on Services/UI/OJS.Services.Ui.Business/Implementations/ParticipantScoresBusinessService.cs
> +                    .Select(ps => new { ParticipantScore = ps, ProblemMaxPoints = ps.Problem.MaximumPoints, Participant=ps.Participant })
Fix spacing

2023-11-02 06:16 UTC, MTsatsarov commented on Services/UI/OJS.Services.Ui.Data/Implementations/ParticipantScoresDataService.cs
> +                    Participant=p,
Fix spacing

2023-11-02 06:16 UTC, MTsatsarov commented on Services/Common/OJS.Services.Common.Data/Implementations/DataService.cs
> +        {
Should be added also to the interface. Add description what means to be executed with timeoutInSeconds = 0

2023-11-02 07:51 UTC, PetarNeshkov commented on Servers/UI/OJS.Servers.Ui/Controllers/Api/ParticipantScoresController.cs
> +    public ParticipantScoresController(IParticipantScoresBusinessService participantScoresBusinessService) =>
Revert '=>' as before

2023-11-02 07:53 UTC, PetarNeshkov commented on Services/UI/OJS.Services.Ui.Business/Implementations/ParticipantsBusinessService.cs
> +    public async Task UpdateTotalScoreSnapshotOfParticipants() =>
Place '=>' on the new line. This is a convention.

2023-11-02 07:55 UTC, PetarNeshkov commented on Services/UI/OJS.Services.Ui.Business/Implementations/ParticipantsBusinessService.cs
> +        foreach (var participantScoreGroup in participantScores)
Try to use .ForEach() whenever you can. This is the better approach.

2023-11-02 07:58 UTC, PetarNeshkov commented on Services/UI/OJS.Services.Ui.Business/Implementations/ParticipantsBusinessService.cs
> +                .AddRange(participantScoreGroup.OrderByDescending(ps => ps.Points).Skip(1)
create a separate variable for the input:
`participantScoreGroup.OrderByDescending(ps => ps.Points)
                                      .Skip(1)`

Also, fix the the indentation:
`participantScoresToRemove.AddRange()
                                              .ToList()`;

2023-11-02 08:03 UTC, PetarNeshkov requested changes
Requesting changes

2023-11-02 13:55 UTC, gogo4ds requested changes

2023-11-02 13:55 UTC, gogo4ds commented on Servers/Administration/OJS.Servers.Administration/Controllers/BackgroundJobsController.cs
> +    }
We have another way of registering jobs - see `BackgroundJobsHostedService`

2023-11-09 13:22 UTC, gogo4ds requested changes

2023-11-09 13:22 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Business/Implementations/RecurringBackgroundJobsBusinessService.cs
> +            OJS.Services.Ui.Business.IParticipantsBusinessService participantsBusinessService)
Administration should not reference Ui. Move logic into Administration's `IParticipantsBusinessService`.

2023-11-09 13:22 UTC, gogo4ds commented on Services/Administration/OJS.Services.Administration.Models/ParticipantScores/Models/CategoryContestsParticipationSummary.cs
> +public class CategoryContestsParticipationSummary
What is this used for?

2023-11-15 08:34 UTC, MTsatsarov approved these changes

2023-11-15 16:40 UTC, SvetoslavUzunov commented on Services/Administration/OJS.Services.Administration.Models/ParticipantScores/Models/CategoryContestsParticipationSummary.cs
> +public class CategoryContestsParticipationSummary
it's fixed

2023-11-21 14:32 UTC, merged