Add check for IsVisible when validating contest
SoftUni-Internal/OpenJudgeSystem pull request #953
Opened 2023-12-04 15:40 UTC by MomchilSt

Closes https://github.com/SoftUni-Internal/exam-systems-issues/issues/1067

**Summary of the changes made**:
1. add check for visible category on contest validation

2023-12-04 15:59 UTC, gogo4ds approved these changes

2023-12-11 15:06 UTC, gogo4ds requested changes

2023-12-11 15:06 UTC, gogo4ds commented on Services/UI/OJS.Services.Ui.Business/Validations/Implementations/Contests/ContestValidationService.cs
> +            ((!contest.IsVisible || !contest.Category!.IsVisible || (contest.Category!.Parent != null && !contest!.Category!.Parent!.IsVisible)) &&
What if the parent has parent? We should check those as well.

2023-12-20 07:30 UTC, shsimeonova submitted a review, later dismissed

2023-12-20 09:58 UTC, gogo4ds submitted a review, later dismissed

2024-01-02 11:00 UTC, gogo4ds requested changes

2024-01-02 11:00 UTC, gogo4ds commented on Services/UI/OJS.Services.Ui.Business/Implementations/ContestCategoriesBusinessService.cs
> +            return this.IsCategoryChildOfInvisibleParentRecursive(categoryWithParent.Parent.ParentId);
Don't you have to provide the `.Parent.Id` here, as with `ParentId` you will skip the Parent's check?

2024-01-03 15:49 UTC, gogo4ds approved these changes

2024-01-04 08:10 UTC, merged